/**
 * Echo-drill lines: tongue twisters only (word-level matching is hard by design).
 */
export const DRILL_SENTENCES = [
  "She sells seashells by the seashore.",
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
  "Peter Piper picked a peck of pickled peppers.",
  "Red leather yellow leather red leather yellow leather.",
  "Unique New York unique New York.",
  "Six slippery snails slid slowly seaward.",
  "Fresh fried fish fish fresh fried.",
  "I saw Susie sitting in a shoeshine shop.",
  "Which wristwatches are Swiss wristwatches?",
  "Thin sticks thick bricks thin sticks thick bricks.",
  "Friendly fleas fireflies fiercely fly forward.",
  "Crisp crusts crackle and crunch.",
  "Toy boat toy boat toy boat.",
  "Really rural really rural.",
  "Black background brown background.",
  "Mixed biscuits mixed biscuits mixed biscuits.",
  "A proper copper coffee pot.",
  "Three free throws three free throws.",
  "Lesser leather never weathered wetter weather better.",
  "I wish to wash my Irish wristwatch.",
  "Round the rugged rocks the ragged rascal ran.",
  "Six sleek swans swam swiftly southwards.",
  "Can you can a can as a canner can can a can?",
  "I scream you scream we all scream for ice cream.",
  "Rubber baby buggy bumpers.",
  "Six sick hicks nick six slick thick bricks.",
  "Selfish shellfish selfish shellfish.",
  "Greek grapes greek grapes.",
  "Shave shops shave shops shave shops.",
  "Flash message flash message flash message.",
  "If two witches watched two watches which witch would watch which watch?",
  "Chester Cheetah chewed a chunk of cheap cheddar cheese.",
  "Eleven benevolent elephants.",
  "Clean clams crammed in clean cans.",
  "Nine nimble noblemen nibbling nuts.",
  "The thirty-three thieves thought that they thrilled the throne throughout Thursday.",
  "Brisk brave brigadiers brandished broad bright blades.",
  "Send toast to ten tense stout saints ten tall tents.",
  "Great gray geese graze gaily daily.",
  "A big black bug bit a big black bear.",
  "Fuzzy Wuzzy was a bear Fuzzy Wuzzy had no hair.",
  "Betty Botter bought some butter but the butter was bitter.",
  "Denise sees the fleece Denise sees the fleece.",
  "Wild wolves watch wise wild woodchucks watch wild wolves.",
  "Six sticky skeletons.",
  "Cows graze in groves on grass which grows in grooves in groves.",
  "Truly rural truly rural truly rural.",
  "Which witch wished which wicked wish?",
  "Six sharp smart sharks.",
  "Quick kiss quick kiss quick kiss.",
  "Fresh French fried fish fillets.",
  "She sees cheese she sees cheese.",
  "Thin Seth at thick thighs thistle sticks.",
  "Twelve twins twirled twelve twigs.",
  "Crazy crows crunched crooked crusty crackers.",
  "Plaid pleated plaid pleated plaid pleated.",
  "Truly tired tadpoles try to tread treacherous trails.",
  "Crisp chips crunch cheerfully.",
  "Silly Sally swiftly shooed seven silly sheep.",
  "Fred fed Ted bread Ted fed Fred bread.",
  "Lucky little lizards lie lounging lazily.",
  "Moose noshing much mushy mango mash.",
  "Plain plane passengers patiently pack plaid parachutes.",
  "Rare rural rabbits race rapidly round rugged rocks.",
  "Shy shy shy shy shy shellfish shop.",
  "Thin things think thick thoughts.",
  "Truly pruny purple plums.",
  "Whistle for the thistle sifter sister.",
  "Six thick thistle sticks.",
  "Creepy crawly crickets creak.",
  "Drew drew drew drew drew drew drew.",
  "Freshly fried flying fish.",
  "Gleaming green grapes grow greatly.",
  "Hassle those hasty hens.",
  "Jolly juggling jesters jeer joyfully.",
  "Knick knack knock knick knack knock.",
  "Little Lilly licked a lemon lollipop.",
  "Many mumbling mice are making merry music.",
  "Noisy noisy noisy noisy nightingale notes.",
  "Polish Polish polish Polish polish.",
  "Quick quacking ducks quack quickly.",
  "Red robots rapidly repair rusty rockets.",
  "Slick slim slippers slide slowly south.",
  "Tiny timid toads try to trot.",
  "Vivid violets vanish very visibly.",
  "Wicked wicker windows which wicked wind warps.",
  "Yellow leather red leather yellow leather red leather.",
  "Zip zap zoom zigzag zip zap zoom.",
  "Blurred blue blood breeds bright blooms.",
  "Chilly cheap chips chill cheaply.",
  "Drippy drippy drops drip downward dramatically.",
  "Fifty-five fine fire fighters fought flaming fires fiercely.",
  "Giggling gaggles of geese gobble grain greedily.",
  "Hiccupping hippos hide huge heaps of hay.",
  "Jumpy jackrabbits jostle jagged jade jars.",
  "Keen keen kittens keep keenly kicking.",
  "Lumpy lumpy lumpy lumpy lumpy loaves.",
  "Mighty mice might make mighty nice mates.",
  "Ninety-nine nimble nymphs nab ninety-nine nuts.",
  "Oddly oval oranges ooze overtly.",
  "Picky picky picky picky picky peacocks.",
  "Quirky quokkas quickly quiz quiet queens.",
  "Rusty rusty rusty rusty rusty rakes.",
  "Snippy snappy snails snap snazzy snacks.",
  "Tippy top typists type tidy titles.",
  "Ugly uncles urge unhappy unicorns uphill.",
  "Vicious vixens vex vexed Vikings.",
  "Wobbly walruses wobble while waving whiskers.",
  "Zany zebras zigzag in zinc zones.",
] as const;

export type DrillSentence = (typeof DRILL_SENTENCES)[number];
